server:
  port: 8080

spring:
  application:
    # 应用名称
    name: reggie
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reggie?useSSL=false
    username: root
    password: 123456
  redis:
    port: 6379
    host: 127.0.0.1
  cache:
    type: redis
    redis:
      time-to-live: 10000
mybatis-plus:
  configuration:
    # 驼峰命名自动映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    local-cache-scope: session
  global-config:
    db-config:
      id-type: assign_id

